// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTvvIEb2Fl5n7CUuMpF5DdTBJmeLs8SFk',
    appId: '1:535518665658:web:f9a96af0b01fbda91d5b83',
    messagingSenderId: '535518665658',
    projectId: 'red-cell-e5cb2',
    authDomain: 'red-cell-e5cb2.firebaseapp.com',
    storageBucket: 'red-cell-e5cb2.appspot.com',
    measurementId: 'G-FFZX70VB7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEltlApqSk8bk2IZD-4Gw8Ij8D2W0zdc',
    appId: '1:535518665658:android:8bbffde534eb816d1d5b83',
    messagingSenderId: '535518665658',
    projectId: 'red-cell-e5cb2',
    storageBucket: 'red-cell-e5cb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYGcCgtVgNTAVlpptYV44oQO_6DKiVS1w',
    appId: '1:535518665658:ios:ebbebd181c57b16d1d5b83',
    messagingSenderId: '535518665658',
    projectId: 'red-cell-e5cb2',
    storageBucket: 'red-cell-e5cb2.appspot.com',
    iosClientId: '535518665658-726rcb4r8srnpfpc48ufmng23feod47h.apps.googleusercontent.com',
    iosBundleId: 'com.example.redCellApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYGcCgtVgNTAVlpptYV44oQO_6DKiVS1w',
    appId: '1:535518665658:ios:ebbebd181c57b16d1d5b83',
    messagingSenderId: '535518665658',
    projectId: 'red-cell-e5cb2',
    storageBucket: 'red-cell-e5cb2.appspot.com',
    iosClientId: '535518665658-726rcb4r8srnpfpc48ufmng23feod47h.apps.googleusercontent.com',
    iosBundleId: 'com.example.redCellApp',
  );
}
